### ISSUE TITLE
Implement CheckInIndex

### ISSUE THREAD

**Issue by kamicut** [kamicut/vote-here-2018#2]
- [ ] Turn the polling stations into an index like in https://github.com/kamicut/vote-here-2016/blob/master/index.js#L10-L33
- [ ] Implement CheckInIndex in LocalForm.js which spits out a polling station location https://github.com/kamicut/vote-here-2016/blob/master/index.js#L62-L75

To simplify things let's start by importing the json into the bundle, and then we can optimize by importing the polling stations in the constructor using an AJAX request. 

NB: In https://raw.githubusercontent.com/kamicut/vote-here-2016/master/data/data.json we don't have place names and have ids because we have english and arabic translations for each place. I don't think we'll have time to do this, so let's do raw strings.

**Comment by kamicut** [comment]
@saeidw I added beirut2 here https://github.com/kamicut/vote-here-2018/blob/master/containers/LocalForm.js#L8

**Comment by kamicut** [comment]
@saeidw could you describe what's needed after we merge in #3 ? You said something about translating the polling center locations?

**Comment by kamicut** [comment]
@developolar can we close this issue?

**Comment by developolar** [comment]
Yes
